# Generated by Django 3.2 on 2023-02-21 01:51

from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(limit_value=4, message='Minimum of four characters are allowed')])),
                ('emailInfo', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('usernameInfo', models.CharField(max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('messageBody', models.TextField()),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to=settings.AUTH_USER_MODEL, verbose_name='messenger')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
