# Generated by Django 3.2 on 2023-02-26 00:39

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(limit_value=4, message='Minimum of four characters are allowed')])),
                ('emailInfo', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('usernameInfo', models.CharField(max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('messageBody', models.TextField()),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
