# Generated by Django 3.2 on 2023-02-26 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price_entry', models.CharField(default='', max_length=20)),
                ('merchant', models.PositiveBigIntegerField(blank=True, null=True)),
                ('merchant_email', models.EmailField(blank=True, max_length=254)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
