# Generated by Django 3.2 on 2023-02-26 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('description', models.TextField()),
                ('price_entry', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('item_image', models.URLField(blank=True, default='https://via.placeholder.com/150/81a4cd/FFFFFF/?text=ITEM', max_length=255)),
                ('on_stock', models.CharField(default='yes', max_length=3)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
